language: php
services:
  - mysql
php:
  - 7.1
  
before_install:
  - sudo apt-get install  memcached
  - sudo service  memcached start
  - git clone https://github.com/websupport-sk/pecl-memcache pecl-memcache
    && cd pecl-memcache
    && phpize
    && ./configure
    && make
    && sudo make install
    && cd ..
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
before_script:
  - composer install --dev
  - cd tests
script: 
  - ../vendor/bin/phpunit -v
after_script:
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v
